#!/opt/exp/bin/expect
#
# test database interface
#
#########################################################################
#
log_user 1;
#
puts "ARGC = $argc";
if {$argc >= 1} {
	strace [lindex $argv 0];
}
#
source $env(LCSTOOLSLIB)/ndb
#
set env(LCSTOOLSDATA) ".";
#
if {[dbdelete junk "A req ^1$ and B req ^2$"] != 0} {
	puts "dbdelete failed.";
} else {
	puts "dbdelete succeeded.";
}
exit 0;

