-- 
-- name name
-- panels panel_id
-- panels equipment_id
-- panels nc_version
-- panels start_time
-- panels end_time
-- panels panel_equipment_id
-- panels panel_source
-- panels panel_trace
-- panels stage_no
-- panels lane_no
-- panels job_id
-- panels setup_id
-- panels trx_product_id
-- name name
-- tracking_data serial_no
-- tracking_data prod_model_no
-- tracking_data panel_id
-- tracking_data pattern_id
-- tracking_data barcode
-- tracking_data setup_id
-- tracking_data top_bottom
-- tracking_data timestamp
-- tracking_data import_flag
-- name name
-- panel_barcode_map module_id
-- panel_barcode_map panel_id
-- panel_barcode_map panel_id_string
-- panel_barcode_map timestamp
-- panel_barcode_map lane_no
-- panel_barcode_map setup_id
-- name name
-- panel_strace_header panel_equipment_id
-- panel_strace_header equipment_id
-- panel_strace_header master_strace_id
-- panel_strace_header panel_strace_id
-- panel_strace_header timestamp
-- panel_strace_header trx_product_id
-- name name
-- panel_strace_details panel_strace_id
-- panel_strace_details reel_id
-- panel_strace_details z_num
-- panel_strace_details pu_num
-- panel_strace_details part_no
-- panel_strace_details custom_area1
-- panel_strace_details custom_area2
-- panel_strace_details custom_area3
-- panel_strace_details custom_area4
-- panel_strace_details feeder_bc
-- name name
-- panel_placement_header panel_equipment_id
-- panel_placement_header equipment_id
-- panel_placement_header master_placement_id
-- panel_placement_header panel_placement_id
-- panel_placement_header timestamp
-- panel_placement_header trx_product_id
-- name name
-- panel_placement_details panel_placement_id
-- panel_placement_details reel_id
-- panel_placement_details nc_placement_id
-- panel_placement_details pattern_no
-- panel_placement_details z_num
-- panel_placement_details pu_num
-- panel_placement_details part_no
-- panel_placement_details custom_area1
-- panel_placement_details custom_area2
-- panel_placement_details custom_area3
-- panel_placement_details custom_area4
-- panel_placement_details ref_designator
-- name name
-- name name
-- reel_data reel_id
-- reel_data part_no
-- reel_data mcid
-- reel_data vendor_no
-- reel_data lot_no
-- reel_data quantity
-- reel_data user_data
-- reel_data reel_barcode
-- reel_data current_quantity
-- reel_data update_time
-- reel_data master_reel_id
-- reel_data create_time
-- reel_data part_class
-- reel_data material_name
-- reel_data prev_reel_id
-- reel_data next_reel_id
-- reel_data adjusted_current_quantity
-- reel_data tray_quantity
-- reel_data bulk_master_id
-- reel_data is_msd
-- name name
-- feeder_counts feeder_id
-- feeder_counts subslot
-- feeder_counts components_fed
-- feeder_counts total_components_fed
-- feeder_counts update_time
-- feeder_counts placement_count
-- feeder_counts total_placement_count
-- feeder_counts pickup_miss
-- feeder_counts total_pickup_miss
-- feeder_counts pickup_error
-- feeder_counts total_pickup_error
-- feeder_counts shape_error
-- feeder_counts total_shape_error
-- feeder_counts recognition_error
-- feeder_counts total_recognition_error
-- name name
-- production_reports_npm_hdr_by_board report_id
-- production_reports_npm_hdr_by_board product_id
-- production_reports_npm_hdr_by_board equipment_id
-- production_reports_npm_hdr_by_board start_time
-- production_reports_npm_hdr_by_board end_time
-- production_reports_npm_hdr_by_board setup_id
-- production_reports_npm_hdr_by_board nc_version
-- production_reports_npm_hdr_by_board lane_no
-- production_reports_npm_hdr_by_board job_id
-- production_reports_npm_hdr_by_board trx_productid
-- production_reports_npm_hdr_by_board stage
-- production_reports_npm_hdr_by_board timestamp
-- production_reports_npm_hdr_by_board prev_report_id
-- name name
-- production_reports_npm_hdr report_id
-- production_reports_npm_hdr product_id
-- production_reports_npm_hdr equipment_id
-- production_reports_npm_hdr start_time
-- production_reports_npm_hdr end_time
-- production_reports_npm_hdr setup_id
-- production_reports_npm_hdr nc_version
-- production_reports_npm_hdr lane_no
-- production_reports_npm_hdr job_id
-- production_reports_npm_hdr trx_productid
-- production_reports_npm_hdr stage
-- production_reports_npm_hdr timestamp
-- name name
-- production_reports_npm_by_board report_id
-- production_reports_npm_by_board total
-- production_reports_npm_by_board actual
-- production_reports_npm_by_board board
-- production_reports_npm_by_board pboard
-- production_reports_npm_by_board module
-- production_reports_npm_by_board hsup
-- production_reports_npm_by_board clean
-- production_reports_npm_by_board brec
-- production_reports_npm_by_board maintenance
-- production_reports_npm_by_board ope_rate
-- production_reports_npm_by_board pickup_rate
-- production_reports_npm_by_board mount_rate
-- production_reports_npm_by_board mount
-- production_reports_npm_by_board recog_err1
-- production_reports_npm_by_board recog_err2
-- production_reports_npm_by_board floortemp
-- production_reports_npm_by_board floorhumid
-- production_reports_npm_by_board mctemp
-- production_reports_npm_by_board mchumid
-- production_reports_npm_by_board thermostatus
-- production_reports_npm_by_board waitt
-- production_reports_npm_by_board poweron
-- production_reports_npm_by_board change
-- production_reports_npm_by_board prodview
-- production_reports_npm_by_board mente
-- production_reports_npm_by_board dataedit
-- production_reports_npm_by_board unitadjust
-- production_reports_npm_by_board idle
-- production_reports_npm_by_board load
-- production_reports_npm_by_board breg
-- production_reports_npm_by_board tpickup
-- production_reports_npm_by_board tpmiss
-- production_reports_npm_by_board trmiss
-- production_reports_npm_by_board tdmiss
-- production_reports_npm_by_board tmmiss
-- production_reports_npm_by_board thmiss
-- production_reports_npm_by_board timestamp
-- production_reports_npm_by_board prod_time
-- production_reports_npm_by_board brcg_time
-- production_reports_npm_by_board othrstop_time
-- production_reports_npm_by_board mhrcgstop_time
-- production_reports_npm_by_board cperr_time
-- production_reports_npm_by_board otherlstop_time
-- production_reports_npm_by_board bndstop_time
-- production_reports_npm_by_board mcfwait_time
-- production_reports_npm_by_board mcrwait_time
-- production_reports_npm_by_board fwait_time
-- production_reports_npm_by_board rwait_time
-- production_reports_npm_by_board swait_time
-- production_reports_npm_by_board cwait_time
-- production_reports_npm_by_board bwait_time
-- production_reports_npm_by_board pwait_time
-- production_reports_npm_by_board scstop_time
-- production_reports_npm_by_board scestop_time
-- production_reports_npm_by_board cnvstop_time
-- production_reports_npm_by_board brcgstop_time
-- production_reports_npm_by_board trbl_time
-- production_reports_npm_by_board fbstop_time
-- production_reports_npm_by_board bndrcgstop_time
-- production_reports_npm_by_board crerr_time
-- production_reports_npm_by_board cderr_time
-- production_reports_npm_by_board cmerr_time
-- production_reports_npm_by_board cterr_time
-- production_reports_npm_by_board trserr_time
-- production_reports_npm_by_board prdstop_time
-- production_reports_npm_by_board judgestop_time
-- production_reports_npm_by_board mount_time
-- production_reports_npm_by_board total_time
-- production_reports_npm_by_board caerr_time
-- production_reports_npm_by_board cpwait_time
-- production_reports_npm_by_board mskrecerrstop_time
-- production_reports_npm_by_board mskpstrecerrstop_time
-- production_reports_npm_by_board bprcgstop_time
-- production_reports_npm_by_board sothrstop_time
-- production_reports_npm_by_board pcustop_time
-- production_reports_npm_by_board bestop_time
-- production_reports_npm_by_board twait_time
-- production_reports_npm_by_board hcwait_time
-- production_reports_npm_by_board hswait_time
-- production_reports_npm_by_board pstrecerrstop_time
-- production_reports_npm_by_board solvnonstop_time
-- production_reports_npm_by_board fwait_count
-- production_reports_npm_by_board rwait_count
-- production_reports_npm_by_board swait_count
-- production_reports_npm_by_board cwait_count
-- production_reports_npm_by_board bwait_count
-- production_reports_npm_by_board pwait_count
-- production_reports_npm_by_board scstop_count
-- production_reports_npm_by_board scestop_count
-- production_reports_npm_by_board othrstop_count
-- production_reports_npm_by_board cnvstop_count
-- production_reports_npm_by_board brcgstop_count
-- production_reports_npm_by_board trbl_count
-- production_reports_npm_by_board mhrcgstop_count
-- production_reports_npm_by_board fbstop_count
-- production_reports_npm_by_board bndrcgstop_count
-- production_reports_npm_by_board cperr_count
-- production_reports_npm_by_board crerr_count
-- production_reports_npm_by_board cderr_count
-- production_reports_npm_by_board cmerr_count
-- production_reports_npm_by_board cterr_count
-- production_reports_npm_by_board trserr_count
-- production_reports_npm_by_board trsmiss_count
-- production_reports_npm_by_board otherlstop_count
-- production_reports_npm_by_board bndstop_count
-- production_reports_npm_by_board tdispense_count
-- production_reports_npm_by_board tpriming_count
-- production_reports_npm_by_board lotboard_count
-- production_reports_npm_by_board lotmodule_count
-- production_reports_npm_by_board mcfwait_count
-- production_reports_npm_by_board mcrwait_count
-- production_reports_npm_by_board caerr_count
-- production_reports_npm_by_board cpwait_count
-- production_reports_npm_by_board mskrecerrstop_count
-- production_reports_npm_by_board mskpstrecerrstop_count
-- production_reports_npm_by_board bprcgstop_count
-- production_reports_npm_by_board sothrstop_count
-- production_reports_npm_by_board pcustop_count
-- production_reports_npm_by_board bestop_count
-- production_reports_npm_by_board twait_count
-- production_reports_npm_by_board hcwait_count
-- production_reports_npm_by_board hswait_count
-- production_reports_npm_by_board pstrecerrstop_count
-- production_reports_npm_by_board total_count
-- production_reports_npm_by_board solvnonstop_count
-- production_reports_npm_by_board spdlenerrstop_time
-- production_reports_npm_by_board spdpstcntupstop_time
-- production_reports_npm_by_board spdpstnonstop_time
-- production_reports_npm_by_board spdpapernonstop_time
-- production_reports_npm_by_board spdmskrecerrstop_time
-- production_reports_npm_by_board spdpstrecerrstop_time
-- production_reports_npm_by_board spdsolvnonstop_time
-- production_reports_npm_by_board spdlenerrstop_count
-- production_reports_npm_by_board spdpstcntupstop_count
-- production_reports_npm_by_board spdpstnonstop_count
-- production_reports_npm_by_board spdpapernonstop_count
-- production_reports_npm_by_board spdmskrecerrstop_count
-- production_reports_npm_by_board spdpstrecerrstop_count
-- production_reports_npm_by_board spdsolvnonstop_count
-- production_reports_npm_by_board spdreccnt_count
-- production_reports_npm_by_board spdprintcnt_count
-- production_reports_npm_by_board spdclncnt_count
-- production_reports_npm_by_board spdpstsupplycnt_count
-- production_reports_npm_by_board spdfbclncnt_count
-- production_reports_npm_by_board spdfbprintcnt_count
-- production_reports_npm_by_board spdrestorationcnt_count
-- production_reports_npm_by_board jwait_time
-- name name
-- production_reports_npm report_id
-- production_reports_npm total
-- production_reports_npm actual
-- production_reports_npm board
-- production_reports_npm pboard
-- production_reports_npm module
-- production_reports_npm hsup
-- production_reports_npm clean
-- production_reports_npm brec
-- production_reports_npm maintenance
-- production_reports_npm ope_rate
-- production_reports_npm pickup_rate
-- production_reports_npm mount_rate
-- production_reports_npm mount
-- production_reports_npm recog_err1
-- production_reports_npm recog_err2
-- production_reports_npm floortemp
-- production_reports_npm floorhumid
-- production_reports_npm mctemp
-- production_reports_npm mchumid
-- production_reports_npm thermostatus
-- production_reports_npm waitt
-- production_reports_npm poweron
-- production_reports_npm change
-- production_reports_npm prodview
-- production_reports_npm mente
-- production_reports_npm dataedit
-- production_reports_npm unitadjust
-- production_reports_npm idle
-- production_reports_npm load
-- production_reports_npm breg
-- production_reports_npm tpickup
-- production_reports_npm tpmiss
-- production_reports_npm trmiss
-- production_reports_npm tdmiss
-- production_reports_npm tmmiss
-- production_reports_npm thmiss
-- production_reports_npm timestamp
-- production_reports_npm prod_time
-- production_reports_npm brcg_time
-- production_reports_npm othrstop_time
-- production_reports_npm mhrcgstop_time
-- production_reports_npm cperr_time
-- production_reports_npm otherlstop_time
-- production_reports_npm bndstop_time
-- production_reports_npm mcfwait_time
-- production_reports_npm mcrwait_time
-- production_reports_npm fwait_time
-- production_reports_npm rwait_time
-- production_reports_npm swait_time
-- production_reports_npm cwait_time
-- production_reports_npm bwait_time
-- production_reports_npm pwait_time
-- production_reports_npm scstop_time
-- production_reports_npm scestop_time
-- production_reports_npm cnvstop_time
-- production_reports_npm brcgstop_time
-- production_reports_npm trbl_time
-- production_reports_npm fbstop_time
-- production_reports_npm bndrcgstop_time
-- production_reports_npm crerr_time
-- production_reports_npm cderr_time
-- production_reports_npm cmerr_time
-- production_reports_npm cterr_time
-- production_reports_npm trserr_time
-- production_reports_npm prdstop_time
-- production_reports_npm judgestop_time
-- production_reports_npm mount_time
-- production_reports_npm total_time
-- production_reports_npm caerr_time
-- production_reports_npm cpwait_time
-- production_reports_npm mskrecerrstop_time
-- production_reports_npm mskpstrecerrstop_time
-- production_reports_npm bprcgstop_time
-- production_reports_npm sothrstop_time
-- production_reports_npm pcustop_time
-- production_reports_npm bestop_time
-- production_reports_npm twait_time
-- production_reports_npm hcwait_time
-- production_reports_npm hswait_time
-- production_reports_npm pstrecerrstop_time
-- production_reports_npm solvnonstop_time
-- production_reports_npm fwait_count
-- production_reports_npm rwait_count
-- production_reports_npm swait_count
-- production_reports_npm cwait_count
-- production_reports_npm bwait_count
-- production_reports_npm pwait_count
-- production_reports_npm scstop_count
-- production_reports_npm scestop_count
-- production_reports_npm othrstop_count
-- production_reports_npm cnvstop_count
-- production_reports_npm brcgstop_count
-- production_reports_npm trbl_count
-- production_reports_npm mhrcgstop_count
-- production_reports_npm fbstop_count
-- production_reports_npm bndrcgstop_count
-- production_reports_npm cperr_count
-- production_reports_npm crerr_count
-- production_reports_npm cderr_count
-- production_reports_npm cmerr_count
-- production_reports_npm cterr_count
-- production_reports_npm trserr_count
-- production_reports_npm trsmiss_count
-- production_reports_npm otherlstop_count
-- production_reports_npm bndstop_count
-- production_reports_npm tdispense_count
-- production_reports_npm tpriming_count
-- production_reports_npm lotboard_count
-- production_reports_npm lotmodule_count
-- production_reports_npm mcfwait_count
-- production_reports_npm mcrwait_count
-- production_reports_npm caerr_count
-- production_reports_npm cpwait_count
-- production_reports_npm mskrecerrstop_count
-- production_reports_npm mskpstrecerrstop_count
-- production_reports_npm bprcgstop_count
-- production_reports_npm sothrstop_count
-- production_reports_npm pcustop_count
-- production_reports_npm bestop_count
-- production_reports_npm twait_count
-- production_reports_npm hcwait_count
-- production_reports_npm hswait_count
-- production_reports_npm pstrecerrstop_count
-- production_reports_npm total_count
-- production_reports_npm solvnonstop_count
-- production_reports_npm spdlenerrstop_time
-- production_reports_npm spdpstcntupstop_time
-- production_reports_npm spdpstnonstop_time
-- production_reports_npm spdpapernonstop_time
-- production_reports_npm spdmskrecerrstop_time
-- production_reports_npm spdpstrecerrstop_time
-- production_reports_npm spdsolvnonstop_time
-- production_reports_npm spdlenerrstop_count
-- production_reports_npm spdpstcntupstop_count
-- production_reports_npm spdpstnonstop_count
-- production_reports_npm spdpapernonstop_count
-- production_reports_npm spdmskrecerrstop_count
-- production_reports_npm spdpstrecerrstop_count
-- production_reports_npm spdsolvnonstop_count
-- production_reports_npm spdreccnt_count
-- production_reports_npm spdprintcnt_count
-- production_reports_npm spdclncnt_count
-- production_reports_npm spdpstsupplycnt_count
-- production_reports_npm spdfbclncnt_count
-- production_reports_npm spdfbprintcnt_count
-- production_reports_npm spdrestorationcnt_count
-- production_reports_npm jwait_time
-- name name
-- production_reports_npm_hdr_raw report_id
-- production_reports_npm_hdr_raw product_id
-- production_reports_npm_hdr_raw equipment_id
-- production_reports_npm_hdr_raw start_time
-- production_reports_npm_hdr_raw end_time
-- production_reports_npm_hdr_raw setup_id
-- production_reports_npm_hdr_raw nc_version
-- production_reports_npm_hdr_raw lane_no
-- production_reports_npm_hdr_raw job_id
-- production_reports_npm_hdr_raw trx_productid
-- production_reports_npm_hdr_raw stage
-- production_reports_npm_hdr_raw timestamp
-- production_reports_npm_hdr_raw prev_report_id
-- name name
-- production_reports_npm_raw report_id
-- production_reports_npm_raw total
-- production_reports_npm_raw actual
-- production_reports_npm_raw board
-- production_reports_npm_raw pboard
-- production_reports_npm_raw module
-- production_reports_npm_raw hsup
-- production_reports_npm_raw clean
-- production_reports_npm_raw brec
-- production_reports_npm_raw maintenance
-- production_reports_npm_raw ope_rate
-- production_reports_npm_raw pickup_rate
-- production_reports_npm_raw mount_rate
-- production_reports_npm_raw mount
-- production_reports_npm_raw recog_err1
-- production_reports_npm_raw recog_err2
-- production_reports_npm_raw floortemp
-- production_reports_npm_raw floorhumid
-- production_reports_npm_raw mctemp
-- production_reports_npm_raw mchumid
-- production_reports_npm_raw thermostatus
-- production_reports_npm_raw waitt
-- production_reports_npm_raw poweron
-- production_reports_npm_raw change
-- production_reports_npm_raw prodview
-- production_reports_npm_raw mente
-- production_reports_npm_raw dataedit
-- production_reports_npm_raw unitadjust
-- production_reports_npm_raw idle
-- production_reports_npm_raw load
-- production_reports_npm_raw breg
-- production_reports_npm_raw tpickup
-- production_reports_npm_raw tpmiss
-- production_reports_npm_raw trmiss
-- production_reports_npm_raw tdmiss
-- production_reports_npm_raw tmmiss
-- production_reports_npm_raw thmiss
-- production_reports_npm_raw timestamp
-- production_reports_npm_raw prod_time
-- production_reports_npm_raw brcg_time
-- production_reports_npm_raw othrstop_time
-- production_reports_npm_raw mhrcgstop_time
-- production_reports_npm_raw cperr_time
-- production_reports_npm_raw otherlstop_time
-- production_reports_npm_raw bndstop_time
-- production_reports_npm_raw mcfwait_time
-- production_reports_npm_raw mcrwait_time
-- production_reports_npm_raw fwait_time
-- production_reports_npm_raw rwait_time
-- production_reports_npm_raw swait_time
-- production_reports_npm_raw cwait_time
-- production_reports_npm_raw bwait_time
-- production_reports_npm_raw pwait_time
-- production_reports_npm_raw scstop_time
-- production_reports_npm_raw scestop_time
-- production_reports_npm_raw cnvstop_time
-- production_reports_npm_raw brcgstop_time
-- production_reports_npm_raw trbl_time
-- production_reports_npm_raw fbstop_time
-- production_reports_npm_raw bndrcgstop_time
-- production_reports_npm_raw crerr_time
-- production_reports_npm_raw cderr_time
-- production_reports_npm_raw cmerr_time
-- production_reports_npm_raw cterr_time
-- production_reports_npm_raw trserr_time
-- production_reports_npm_raw prdstop_time
-- production_reports_npm_raw judgestop_time
-- production_reports_npm_raw mount_time
-- production_reports_npm_raw total_time
-- production_reports_npm_raw caerr_time
-- production_reports_npm_raw cpwait_time
-- production_reports_npm_raw mskrecerrstop_time
-- production_reports_npm_raw mskpstrecerrstop_time
-- production_reports_npm_raw bprcgstop_time
-- production_reports_npm_raw sothrstop_time
-- production_reports_npm_raw pcustop_time
-- production_reports_npm_raw bestop_time
-- production_reports_npm_raw twait_time
-- production_reports_npm_raw hcwait_time
-- production_reports_npm_raw hswait_time
-- production_reports_npm_raw pstrecerrstop_time
-- production_reports_npm_raw solvnonstop_time
-- production_reports_npm_raw fwait_count
-- production_reports_npm_raw rwait_count
-- production_reports_npm_raw swait_count
-- production_reports_npm_raw cwait_count
-- production_reports_npm_raw bwait_count
-- production_reports_npm_raw pwait_count
-- production_reports_npm_raw scstop_count
-- production_reports_npm_raw scestop_count
-- production_reports_npm_raw othrstop_count
-- production_reports_npm_raw cnvstop_count
-- production_reports_npm_raw brcgstop_count
-- production_reports_npm_raw trbl_count
-- production_reports_npm_raw mhrcgstop_count
-- production_reports_npm_raw fbstop_count
-- production_reports_npm_raw bndrcgstop_count
-- production_reports_npm_raw cperr_count
-- production_reports_npm_raw crerr_count
-- production_reports_npm_raw cderr_count
-- production_reports_npm_raw cmerr_count
-- production_reports_npm_raw cterr_count
-- production_reports_npm_raw trserr_count
-- production_reports_npm_raw trsmiss_count
-- production_reports_npm_raw otherlstop_count
-- production_reports_npm_raw bndstop_count
-- production_reports_npm_raw tdispense_count
-- production_reports_npm_raw tpriming_count
-- production_reports_npm_raw lotboard_count
-- production_reports_npm_raw lotmodule_count
-- production_reports_npm_raw mcfwait_count
-- production_reports_npm_raw mcrwait_count
-- production_reports_npm_raw caerr_count
-- production_reports_npm_raw cpwait_count
-- production_reports_npm_raw mskrecerrstop_count
-- production_reports_npm_raw mskpstrecerrstop_count
-- production_reports_npm_raw bprcgstop_count
-- production_reports_npm_raw sothrstop_count
-- production_reports_npm_raw pcustop_count
-- production_reports_npm_raw bestop_count
-- production_reports_npm_raw twait_count
-- production_reports_npm_raw hcwait_count
-- production_reports_npm_raw hswait_count
-- production_reports_npm_raw pstrecerrstop_count
-- production_reports_npm_raw total_count
-- production_reports_npm_raw solvnonstop_count
-- production_reports_npm_raw spdlenerrstop_time
-- production_reports_npm_raw spdpstcntupstop_time
-- production_reports_npm_raw spdpstnonstop_time
-- production_reports_npm_raw spdpapernonstop_time
-- production_reports_npm_raw spdmskrecerrstop_time
-- production_reports_npm_raw spdpstrecerrstop_time
-- production_reports_npm_raw spdsolvnonstop_time
-- production_reports_npm_raw spdlenerrstop_count
-- production_reports_npm_raw spdpstcntupstop_count
-- production_reports_npm_raw spdpstnonstop_count
-- production_reports_npm_raw spdpapernonstop_count
-- production_reports_npm_raw spdmskrecerrstop_count
-- production_reports_npm_raw spdpstrecerrstop_count
-- production_reports_npm_raw spdsolvnonstop_count
-- production_reports_npm_raw spdreccnt_count
-- production_reports_npm_raw spdprintcnt_count
-- production_reports_npm_raw spdclncnt_count
-- production_reports_npm_raw spdpstsupplycnt_count
-- production_reports_npm_raw spdfbclncnt_count
-- production_reports_npm_raw spdfbprintcnt_count
-- production_reports_npm_raw spdrestorationcnt_count
-- production_reports_npm_raw jwait_time
-- name name
-- z_cass_npm_hdr_by_board report_id
-- z_cass_npm_hdr_by_board product_id
-- z_cass_npm_hdr_by_board equipment_id
-- z_cass_npm_hdr_by_board start_time
-- z_cass_npm_hdr_by_board end_time
-- z_cass_npm_hdr_by_board setup_id
-- z_cass_npm_hdr_by_board nc_version
-- z_cass_npm_hdr_by_board lane_no
-- z_cass_npm_hdr_by_board job_id
-- z_cass_npm_hdr_by_board trx_productid
-- z_cass_npm_hdr_by_board stage
-- z_cass_npm_hdr_by_board timestamp
-- z_cass_npm_hdr_by_board prev_report_id
-- name name
-- z_cass_npm_hdr report_id
-- z_cass_npm_hdr product_id
-- z_cass_npm_hdr equipment_id
-- z_cass_npm_hdr start_time
-- z_cass_npm_hdr end_time
-- z_cass_npm_hdr setup_id
-- z_cass_npm_hdr nc_version
-- z_cass_npm_hdr lane_no
-- z_cass_npm_hdr job_id
-- z_cass_npm_hdr trx_productid
-- z_cass_npm_hdr stage
-- z_cass_npm_hdr timestamp
-- name name
-- z_cass_npm_by_board report_id
-- z_cass_npm_by_board lot
-- z_cass_npm_by_board stage
-- z_cass_npm_by_board tprod
-- z_cass_npm_by_board head
-- z_cass_npm_by_board fadd
-- z_cass_npm_by_board fsadd
-- z_cass_npm_by_board fblkcode
-- z_cass_npm_by_board fblkserial
-- z_cass_npm_by_board reelid
-- z_cass_npm_by_board tcnt
-- z_cass_npm_by_board tmiss
-- z_cass_npm_by_board rmiss
-- z_cass_npm_by_board hmiss
-- z_cass_npm_by_board fmiss
-- z_cass_npm_by_board mmiss
-- z_cass_npm_by_board board
-- z_cass_npm_by_board partsname
-- z_cass_npm_by_board place_count
-- z_cass_npm_by_board trsmiss
-- z_cass_npm_by_board timestamp
-- z_cass_npm_by_board reel_id
-- z_cass_npm_by_board feeder_id
-- name name
-- z_cass_npm report_id
-- z_cass_npm lot
-- z_cass_npm stage
-- z_cass_npm tprod
-- z_cass_npm head
-- z_cass_npm fadd
-- z_cass_npm fsadd
-- z_cass_npm fblkcode
-- z_cass_npm fblkserial
-- z_cass_npm reelid
-- z_cass_npm tcnt
-- z_cass_npm tmiss
-- z_cass_npm rmiss
-- z_cass_npm hmiss
-- z_cass_npm fmiss
-- z_cass_npm mmiss
-- z_cass_npm board
-- z_cass_npm partsname
-- z_cass_npm place_count
-- z_cass_npm trsmiss
-- z_cass_npm timestamp
-- z_cass_npm reel_id
-- z_cass_npm feeder_id
-- name name
-- z_cass_npm_hdr_raw report_id
-- z_cass_npm_hdr_raw product_id
-- z_cass_npm_hdr_raw equipment_id
-- z_cass_npm_hdr_raw start_time
-- z_cass_npm_hdr_raw end_time
-- z_cass_npm_hdr_raw setup_id
-- z_cass_npm_hdr_raw nc_version
-- z_cass_npm_hdr_raw lane_no
-- z_cass_npm_hdr_raw job_id
-- z_cass_npm_hdr_raw trx_productid
-- z_cass_npm_hdr_raw stage
-- z_cass_npm_hdr_raw timestamp
-- z_cass_npm_hdr_raw prev_report_id
-- name name
-- z_cass_npm_raw report_id
-- z_cass_npm_raw lot
-- z_cass_npm_raw stage
-- z_cass_npm_raw tprod
-- z_cass_npm_raw head
-- z_cass_npm_raw fadd
-- z_cass_npm_raw fsadd
-- z_cass_npm_raw fblkcode
-- z_cass_npm_raw fblkserial
-- z_cass_npm_raw reelid
-- z_cass_npm_raw tcnt
-- z_cass_npm_raw tmiss
-- z_cass_npm_raw rmiss
-- z_cass_npm_raw hmiss
-- z_cass_npm_raw fmiss
-- z_cass_npm_raw mmiss
-- z_cass_npm_raw board
-- z_cass_npm_raw partsname
-- z_cass_npm_raw place_count
-- z_cass_npm_raw trsmiss
-- z_cass_npm_raw timestamp
-- z_cass_npm_raw reel_id
-- z_cass_npm_raw feeder_id
-- name name
-- nozzle_npm_hdr_by_board report_id
-- nozzle_npm_hdr_by_board product_id
-- nozzle_npm_hdr_by_board equipment_id
-- nozzle_npm_hdr_by_board start_time
-- nozzle_npm_hdr_by_board end_time
-- nozzle_npm_hdr_by_board setup_id
-- nozzle_npm_hdr_by_board nc_version
-- nozzle_npm_hdr_by_board lane_no
-- nozzle_npm_hdr_by_board job_id
-- nozzle_npm_hdr_by_board trx_productid
-- nozzle_npm_hdr_by_board stage
-- nozzle_npm_hdr_by_board timestamp
-- nozzle_npm_hdr_by_board prev_report_id
-- name name
-- nozzle_npm_hdr report_id
-- nozzle_npm_hdr product_id
-- nozzle_npm_hdr equipment_id
-- nozzle_npm_hdr start_time
-- nozzle_npm_hdr end_time
-- nozzle_npm_hdr setup_id
-- nozzle_npm_hdr nc_version
-- nozzle_npm_hdr lane_no
-- nozzle_npm_hdr job_id
-- nozzle_npm_hdr trx_productid
-- nozzle_npm_hdr stage
-- nozzle_npm_hdr timestamp
-- name name
-- nozzle_npm_by_board report_id
-- nozzle_npm_by_board lot
-- nozzle_npm_by_board stage
-- nozzle_npm_by_board tprod
-- nozzle_npm_by_board head
-- nozzle_npm_by_board ncadd
-- nozzle_npm_by_board nhadd
-- nozzle_npm_by_board tcnt
-- nozzle_npm_by_board tmiss
-- nozzle_npm_by_board rmiss
-- nozzle_npm_by_board hmiss
-- nozzle_npm_by_board board
-- nozzle_npm_by_board nozzlenum
-- nozzle_npm_by_board nblkcode
-- nozzle_npm_by_board nblkserial
-- nozzle_npm_by_board fmiss
-- nozzle_npm_by_board mmiss
-- nozzle_npm_by_board place_count
-- nozzle_npm_by_board trsmiss
-- nozzle_npm_by_board timestamp
-- name name
-- nozzle_npm report_id
-- nozzle_npm lot
-- nozzle_npm stage
-- nozzle_npm tprod
-- nozzle_npm head
-- nozzle_npm ncadd
-- nozzle_npm nhadd
-- nozzle_npm tcnt
-- nozzle_npm tmiss
-- nozzle_npm rmiss
-- nozzle_npm hmiss
-- nozzle_npm board
-- nozzle_npm nozzlenum
-- nozzle_npm nblkcode
-- nozzle_npm nblkserial
-- nozzle_npm fmiss
-- nozzle_npm mmiss
-- nozzle_npm place_count
-- nozzle_npm trsmiss
-- nozzle_npm timestamp
-- name name
-- nozzle_npm_hdr_raw report_id
-- nozzle_npm_hdr_raw product_id
-- nozzle_npm_hdr_raw equipment_id
-- nozzle_npm_hdr_raw start_time
-- nozzle_npm_hdr_raw end_time
-- nozzle_npm_hdr_raw setup_id
-- nozzle_npm_hdr_raw nc_version
-- nozzle_npm_hdr_raw lane_no
-- nozzle_npm_hdr_raw job_id
-- nozzle_npm_hdr_raw trx_productid
-- nozzle_npm_hdr_raw stage
-- nozzle_npm_hdr_raw timestamp
-- nozzle_npm_hdr_raw prev_report_id
-- name name
-- nozzle_npm_raw report_id
-- nozzle_npm_raw lot
-- nozzle_npm_raw stage
-- nozzle_npm_raw tprod
-- nozzle_npm_raw head
-- nozzle_npm_raw ncadd
-- nozzle_npm_raw nhadd
-- nozzle_npm_raw tcnt
-- nozzle_npm_raw tmiss
-- nozzle_npm_raw rmiss
-- nozzle_npm_raw hmiss
-- nozzle_npm_raw board
-- nozzle_npm_raw nozzlenum
-- nozzle_npm_raw nblkcode
-- nozzle_npm_raw nblkserial
-- nozzle_npm_raw fmiss
-- nozzle_npm_raw mmiss
-- nozzle_npm_raw place_count
-- nozzle_npm_raw trsmiss
-- nozzle_npm_raw timestamp
-- name name
-- product_spc_npm productid
-- product_spc_npm programid
-- product_spc_npm stage
-- product_spc_npm timestamp
-- name name
-- product_run_history product_run_history_id
-- product_run_history equipment_id
-- product_run_history lane_no
-- product_run_history setup_id
-- product_run_history start_time
-- product_run_history end_time
-- name name
-- nc_detail nc_version
-- nc_detail cassette
-- nc_detail slot
-- nc_detail subslot
-- nc_detail tva
-- name name
-- dgs_nc_placement_detail dgs_product_data_id
-- dgs_nc_placement_detail dgs_product_setup_id
-- dgs_nc_placement_detail idnum
-- dgs_nc_placement_detail ref_designator
-- dgs_nc_placement_detail part_name
-- dgs_nc_placement_detail pattern_number
-- name name
-- nc_placement_detail nc_placement_id
-- nc_placement_detail idnum
-- nc_placement_detail ref_designator
-- nc_placement_detail part_name
-- nc_placement_detail pattern_number
-- nc_placement_detail nc_version
-- name name
-- dgs_nc_summary dgs_product_data_id
-- dgs_nc_summary physical_equipment_id
-- dgs_nc_summary dgs_glue_total
-- name name
-- nc_summary setup_id
-- nc_summary equipment_id
-- nc_summary nc_version
-- nc_summary tva
-- nc_summary double_feeder_flag
-- nc_summary glue_total
-- nc_summary solder_total
-- name name
-- system_config attribute_name
-- system_config attribute_value
-- name name
-- product_setup product_id
-- product_setup route_id
-- product_setup mix_name
-- product_setup setup_id
-- product_setup ldf_file_name
-- product_setup machine_file_name
-- product_setup setup_valid_flag
-- product_setup last_modified_time
-- product_setup dos_file_name
-- product_setup model_string
-- product_setup top_bottom
-- product_setup pt_group_name
-- product_setup pt_lot_name
-- product_setup pt_mc_file_name
-- product_setup pt_downloaded_flag
-- product_setup pt_needs_download
-- product_setup sub_parts_flag
-- product_setup barcode_side
-- product_setup cycle_time
-- product_setup import_source
-- product_setup modified_import_source
-- product_setup theoretical_xover_time
-- product_setup publish_mode
-- product_setup master_mjs_id
-- product_setup pcb_name
-- name name
-- product_data product_id
-- product_data product_name
-- product_data dos_product_name
-- product_data patterns_per_panel
-- product_data panel_width
-- product_data panel_length
-- product_data panel_thickness
-- product_data camera_xaxis_top
-- product_data camera_yaxis_top
-- product_data camera_xaxis_bottom
-- product_data camera_yaxis_bottom
-- product_data tooling_pin_distance
-- product_data barcodes_per_panel
-- product_data product_valid_flag
-- product_data tooling_pin
-- product_data conveyor_speed
-- product_data use_brd_file
-- product_data base_product_id
--
-- equipment equipment_id 
-- equipment equipment_name 
-- equipment equipment_type 
-- equipment icon_filename 
-- equipment valid_flag 
-- equipment equipment_abbr 
-- equipment pmd_priority_group_id 
-- 
-- select 
--     r.route_id as            'r.route_id',
--     r.route_name as          'r.route_name',
--     rl.pos as                'rl.pos',
--     rl.zone_id as            'rl.zone_id',
--     z.zone_name as           'z.zone_name',
--     z.trace_level as         'z.trace_level',
--     z.module_id as           'z.module_id',
--     zl.pos as                'zl.pos',
--     zl.equipment_id as       'zl.equipment_id',
--     eq.equipment_name as     'eq.equipment_name',
--     ph.equipment_id as       'ph.equipment_id',
--     ph.panel_equipment_id as 'ph.panel_equipment_id',
--     ph.trx_product_id as     'ph.trx_product_id',
--     ph.master_placement_id as   'ph.master_placement_id',
--     ph.panel_placement_id as    'ph.panel_placement_id',
--     ph.timestamp as          'ph.timestamp',
--     p.panel_id as            'p.panel_id',
--     p.equipment_id as        'p.equipment_id',
--     p.nc_version as          'p.nc_version',
--     p.start_time as          'p.start_time',
--     p.end_time as            'p.end_time',
--     p.panel_equipment_id as  'p.panel_equipment_id',
--     p.panel_source as        'p.panel_source',
--     p.panel_trace as         'p.panel_trace',
--     p.stage_no as            'p.stage_no',
--     p.lane_no as             'p.lane_no',
--     p.job_id as              'p.job_id',
--     p.setup_id as            'p.setup_id',
--     p.trx_product_id as      'p.trx_product_id',
--     td.serial_no as          'td.serial_no',
--     td.barcode as            'td.barcode',
--     td.prod_model_no as      'td.prod_model_no',
--     td.panel_id as           'td.panel_id',
--     td.pattern_id as         'td.pattern_id',
--     td.setup_id as           'td.setup_id',
--     td.top_bottom as         'td.top_bottom',
--     td.timestamp as          'td.timestamp',
--     td.import_flag as        'td.import_flag',
--     pd.panel_placement_id as 'pd.panel_placement_id',
--     pd.reel_id as            'pd.reel_id',
--     pd.nc_placement_id as    'pd.nc_placement_id',
--     pd.pattern_no as         'pd.pattern_no',
--     pd.z_num as              'pd.z_num',
--     pd.pu_num as             'pd.pu_num',
--     pd.part_no as            'pd.part_no',
--     pd.custom_area1 as       'pd.custom_area1',
--     pd.custom_area2 as       'pd.custom_area2',
--     pd.custom_area3 as       'pd.custom_area3',
--     pd.custom_area4 as       'pd.custom_area4',
--     pd.ref_designator as     'pd.ref_designator'
-- from
--     routes r
-- inner join
--     route_layout rl
-- on
--     rl.route_id = r.route_id
-- inner join
--     zones z
-- on
--     z.zone_id = rl.zone_id
-- inner join
--     zone_layout zl
-- on
--     zl.zone_id = rl.zone_id
-- inner join
--     equipment eq
-- on
--     eq.equipment_id = zl.equipment_id
-- left join
--     panel_placement_header ph
-- on
--     ph.equipment_id = zl.equipment_id
-- left join
--     panels p
-- on
--     p.panel_equipment_id = ph.panel_equipment_id
-- left join
--     tracking_data td
-- on
--     td.panel_id = p.panel_id
-- left join
--     panel_placement_details pd
-- on
--     pd.panel_placement_id = ph.master_placement_id
-- where
--     r.valid_flag = 't'
-- and
--     z.valid_flag = 't'
-- and
--     z.module_id > 0
-- and
--     1422842400 <= ph.timestamp
-- and
--     ph.timestamp < 1422846000
-- and
--     eq.equipment_name like 'L3-2-CM602-1%'
-- order by
--     r.route_id asc,
--     rl.pos asc,
--     ph.equipment_id asc,
--     td.serial_no asc,
--     p.stage_no asc,
--     p.lane_no asc,
--     ph.panel_equipment_id asc
-- go
-- 
select 
    -- top (100)
    r.route_name as          'r.route_name',
    td.panel_id as           'td.panel_id',
    eq.equipment_name as     'eq.equipment_name',
    p.lane_no as             'p.lane_no',
    p.stage_no as            'p.stage_no',
    -- r.route_id as            'r.route_id',
    -- rl.pos as                'rl.pos',
    -- rl.zone_id as            'rl.zone_id',
    -- z.zone_name as           'z.zone_name',
    -- z.trace_level as         'z.trace_level',
    -- z.module_id as           'z.module_id',
    -- zl.pos as                'zl.pos',
    -- zl.equipment_id as       'zl.equipment_id',
    -- p.panel_id as            'p.panel_id',
    -- p.equipment_id as        'p.equipment_id',
    p.nc_version as          'p.nc_version',
    -- p.start_time as          'p.start_time',
    p.end_time as            'p.end_time',
    -- p.panel_equipment_id as  'p.panel_equipment_id',
    -- p.panel_source as        'p.panel_source',
    -- p.panel_trace as         'p.panel_trace',
    -- p.job_id as              'p.job_id',
    -- p.setup_id as            'p.setup_id',
    p.trx_product_id as      'p.trx_product_id',
    td.serial_no as          'td.serial_no',
    td.barcode as            'td.barcode',
    td.prod_model_no as      'td.prod_model_no',
    td.pattern_id as         'td.pattern_id',
    td.setup_id as           'td.setup_id',
    td.top_bottom as         'td.top_bottom',
    td.timestamp as          'td.timestamp',
    td.import_flag as        'td.import_flag',
    pph.panel_equipment_id as  'pph.panel_equipment_id',
    pph.equipment_id as        'pph.equipment_id',
    pph.master_placement_id as 'pph.master_placement_id',
    pph.panel_placement_id as  'pph.panel_placement_id',
    pph.timestamp as           'pph.timestamp',
    pph.trx_product_id as      'pph.trx_product_id',
    count(ppd.panel_placement_id) as 'count_ppd.panel_placement_id'
    -- ppd.panel_placement_id as 'ppd.panel_placement_id',
    -- ppd.reel_id as            'ppd.reel_id',
    -- ppd.nc_placement_id as    'ppd.nc_placement_id',
    -- ppd.pattern_no as         'ppd.pattern_no',
    -- ppd.z_num as              'ppd.z_num',
    -- ppd.pu_num as             'ppd.pu_num',
    -- ppd.part_no as            'ppd.part_no',
    -- ppd.custom_area1 as       'ppd.custom_area1',
    -- ppd.custom_area2 as       'ppd.custom_area2',
    -- ppd.custom_area3 as       'ppd.custom_area3',
    -- ppd.custom_area4 as       'ppd.custom_area4',
    -- ppd.ref_designator as     'ppd.ref_designator'
from
    routes r
inner join
    route_layout rl
on
    rl.route_id = r.route_id
inner join
    zones z
on
    z.zone_id = rl.zone_id
inner join
    zone_layout zl
on
    zl.zone_id = rl.zone_id
inner join
    equipment eq
on
    eq.equipment_id = zl.equipment_id
inner join
    panels p
on
    p.equipment_id = zl.equipment_id
inner join
    tracking_data td
on
    td.panel_id = p.panel_id
left join
    panel_placement_header pph
on
    pph.equipment_id = zl.equipment_id
and
    pph.panel_equipment_id = p.panel_equipment_id
left join
    panel_placement_details ppd
on
    ppd.panel_placement_id = pph.master_placement_id
where
    r.valid_flag = 't'
and
    z.valid_flag = 't'
and
    z.module_id > 0
and
    1422842400 <= p.end_time
and
    p.end_time < 1422846000
group by
    r.route_id,
    r.route_name,
    td.panel_id,
    rl.pos,
    eq.equipment_name,
    p.lane_no,
    p.stage_no,
    p.nc_version,
    p.end_time,
    p.trx_product_id,
    td.serial_no,
    td.barcode,
    td.prod_model_no,
    td.pattern_id,
    td.setup_id,
    td.top_bottom,
    td.timestamp,
    td.import_flag,
    pph.panel_equipment_id,
    pph.equipment_id,
    pph.master_placement_id,
    pph.panel_placement_id,
    pph.timestamp,
    pph.trx_product_id
order by
    r.route_id asc,
    td.panel_id asc,
    rl.pos asc,
    p.lane_no asc,
    p.stage_no asc
go

