
create view u03.mqt_pos_data_view
as
select
    mqt._filename_route as mqt_filename_route,
    mqt._machine_order as mqt_machine_order,
    mqt._lane_no as mqt_lane_no,
    mqt._stage_no as mqt_stage_no,
    mqt._filename_timestamp as mqt_filename_timestamp,
    mqt._filename_id as mqt_filename_id,
    mqt._pcb_serial as mqt_pcb_serial,
    mqt._pcb_id as mqt_pcb_id,
    mqt._output_no as mqt_output_no,
    mqt._pcb_id_lot_no as mqt_pcb_id_lot_no,
    mqt._pcb_id_serial_no as mqt_pcb_id_serial_no,
    mqt._mjsid as mqt_mjsid,
    mqt._bcrstatus as mqt_bcrstatus,
    mqt._code as mqt_code,
    mqt._lane as mqt_lane,
    mqt._lotname as mqt_lotname,
    mqt._lotnumber as mqt_lotnumber,
    mqt._output as mqt_output,
    mqt._planid as mqt_planid,
    mqt._productid as mqt_productid,
    mqt._rev as mqt_rev,
    mqt._serial as mqt_serial,
    mqt._serialstatus as mqt_serialstatus,
    mqt._stage as mqt_stage,
    mqt._b as mqt_b,
    mqt._idnum as mqt_idnum,
    mqt._turn as mqt_turn,
    mqt._ms as mqt_ms,
    mqt._ts as mqt_ts,
    mqt._fadd as mqt_fadd,
    mqt._fsadd as mqt_fsadd,
    mqt._nhadd as mqt_nhadd,
    mqt._ncadd as mqt_ncadd,
    mqt._fblkcode as mqt_fblkcode,
    mqt._fblkserial as mqt_fblkserial,
    mqt._nblkcode as mqt_nblkcode,
    mqt._nblkserial as mqt_nblkserial,
    mqt._reelid as mqt_reelid,
    mqt._f as mqt_f,
    mqt._rcgx as mqt_rcgx,
    mqt._rcgy as mqt_rcgy,
    mqt._rcga as mqt_rcga,
    mqt._tcx as mqt_tcx,
    mqt._tcy as mqt_tcy,
    mqt._mposirecx as mqt_mposirecx,
    mqt._mposirecy as mqt_mposirecy,
    mqt._mposireca as mqt_mposireca,
    mqt._mposirecz as mqt_mposirecz,
    mqt._thmax as mqt_thmax,
    mqt._thave as mqt_thave,
    mqt._mntcx as mqt_mntcx,
    mqt._mntcy as mqt_mntcy,
    mqt._mntca as mqt_mntca,
    mqt._tlx as mqt_tlx,
    mqt._tly as mqt_tly,
    mqt._inspectarea as mqt_inspectarea,
    mqt._didnum as mqt_didnum,
    mqt._ds as mqt_ds,
    mqt._dispenseid as mqt_dispenseid,
    mqt._parts as mqt_parts,
    mqt._warpz as mqt_warpz,
    mqt._prepickuplot as mqt_prepickuplot,
    mqt._prepickupsts as mqt_prepickupsts,
    pos._filename_route as pos_filename_route,
    pos._filename_timestamp as pos_filename_timestamp,
    pos._filename as pos_filename,
    pos._filename_type as pos_filename_type,
    pos._filename_id as pos_filename_id,
    pos._history_id as pos_history_id,
    pos._time_stamp as pos_time_stamp,
    pos._crb_file_name as pos_crb_file_name,
    pos._product_name as pos_product_name,
    pos.lot_idnum as pos_lot_idnum,
    pos._lotnum as pos_lotnum,
    pos._lot as pos_lot,
    pos._mcfilename as pos_mcfilename,
    pos._filter as pos_filter,
    pos._autochg as pos_autochg,
    pos._basechg as pos_basechg,
    pos._lane as pos_lane,
    pos._productionid as pos_productionid,
    pos._simproduct as pos_simproduct,
    pos._dgspcbname as pos_dgspcbname,
    pos._dgspcbrev as pos_dgspcbrev,
    pos._dgspcbside as pos_dgspcbside,
    pos._dgsrefpin as pos_dgsrefpin,
    pos.lot_c as pos_lot_c,
    pos._datagenmode as pos_datagenmode,
    pos._mounthead as pos_mounthead,
    pos._vstpath as pos_vstpath,
    pos._targettact as pos_targettact,
    pos._order as pos_order,
    pos._lot_number as pos_lot_number,
    pos.pos_idnum as pos_idnum,
    pos._cadid as pos_cadid,
    pos._x as pos_x,
    pos._y as pos_y,
    pos._a as pos_a,
    pos._parts as pos_parts,
    pos._brm as pos_brm,
    pos._turn as pos_turn,
    pos._dturn as pos_dturn,
    pos._ts as pos_ts,
    pos._ms as pos_ms,
    pos._ds as pos_ds,
    pos._np as pos_np,
    pos._dnp as pos_dnp,
    pos._pu as pos_pu,
    pos._side as pos_side,
    pos._dpu as pos_dpu,
    pos._head as pos_head,
    pos._dhead as pos_dhead,
    pos._ihead as pos_ihead,
    pos._b as pos_b,
    pos._pg as pos_pg,
    pos._s as pos_s,
    pos._rid as pos_rid,
    pos.pos_c as pos_c,
    pos._m as pos_m,
    pos._mb as pos_mb,
    pos._f as pos_f,
    pos._pr as pos_pr,
    pos._priseq as pos_priseq,
    pos._p as pos_p,
    pos._pad as pos_pad,
    pos._vw as pos_vw,
    pos._stdpos as pos_stdpos,
    pos._land as pos_land,
    pos._depend as pos_depend,
    pos._chkflag as pos_chkflag,
    pos._exchk as pos_exchk,
    pos._grand as pos_grand,
    pos._marea as pos_marea,
    pos._rmset as pos_rmset,
    pos._sh as pos_sh,
    pos._scandir1 as pos_scandir1,
    pos._scandir2 as pos_scandir2,
    pos._ohl as pos_ohl,
    pos._ohr as pos_ohr,
    pos._apcctrl as pos_apcctrl,
    pos._wg as pos_wg,
    pos._skipnumber as pos_skipnumber

from
    u03.index_info_mqt_no_view mqt
inner join
    crb.lot_position_data_no_view pos
on
    upper(pos._crb_file_name) = upper(mqt._mjsid)
and
    upper(pos._lot) = upper(mqt._lotname)
and
    pos.pos_idnum = mqt._idnum
;

create view u03.mqt_pos_data_aoi_no_good_view
as
select
    mqt._filename_route as     mqt_filename_route,
    mqt._machine_order as      mqt_machine_order,
    mqt._lane_no as            mqt_lane_no,
    mqt._stage_no as           mqt_stage_no,
    mqt._filename_timestamp as mqt_filename_timestamp,
    mqt._filename_id as        mqt_filename_id,
    mqt._pcb_serial as         mqt_pcb_serial,
    mqt._pcb_id as             mqt_pcb_id,
    mqt._output_no as          mqt_output_no,
    mqt._pcb_id_lot_no as      mqt_pcb_id_lot_no,
    mqt._pcb_id_serial_no as   mqt_pcb_id_serial_no,
    mqt._mjsid as              mqt_mjsid,
    mqt._bcrstatus as          mqt_bcrstatus,
    mqt._code as               mqt_code,
    mqt._lane as               mqt_lane,
    mqt._lotname as            mqt_lotname,
    mqt._lotnumber as          mqt_lotnumber,
    mqt._output as             mqt_output,
    mqt._planid as             mqt_planid,
    mqt._productid as          mqt_productid,
    mqt._rev as                mqt_rev,
    mqt._serial as             mqt_serial,
    mqt._serialstatus as       mqt_serialstatus,
    mqt._stage as              mqt_stage,
    mqt._b as                  mqt_b,
    mqt._idnum as              mqt_idnum,
    mqt._turn as               mqt_turn,
    mqt._ms as                 mqt_ms,
    mqt._ts as                 mqt_ts,
    mqt._fadd as               mqt_fadd,
    mqt._fsadd as              mqt_fsadd,
    mqt._nhadd as              mqt_nhadd,
    mqt._ncadd as              mqt_ncadd,
    mqt._fblkcode as           mqt_fblkcode,
    mqt._fblkserial as         mqt_fblkserial,
    mqt._nblkcode as           mqt_nblkcode,
    mqt._nblkserial as         mqt_nblkserial,
    mqt._reelid as             mqt_reelid,
    mqt._f as                  mqt_f,
    mqt._rcgx as               mqt_rcgx,
    mqt._rcgy as               mqt_rcgy,
    mqt._rcga as               mqt_rcga,
    mqt._tcx as                mqt_tcx,
    mqt._tcy as                mqt_tcy,
    mqt._mposirecx as          mqt_mposirecx,
    mqt._mposirecy as          mqt_mposirecy,
    mqt._mposireca as          mqt_mposireca,
    mqt._mposirecz as          mqt_mposirecz,
    mqt._thmax as              mqt_thmax,
    mqt._thave as              mqt_thave,
    mqt._mntcx as              mqt_mntcx,
    mqt._mntcy as              mqt_mntcy,
    mqt._mntca as              mqt_mntca,
    mqt._tlx as                mqt_tlx,
    mqt._tly as                mqt_tly,
    mqt._inspectarea as        mqt_inspectarea,
    mqt._didnum as             mqt_didnum,
    mqt._ds as                 mqt_ds,
    mqt._dispenseid as         mqt_dispenseid,
    mqt._parts as              mqt_parts,
    mqt._warpz as              mqt_warpz,
    mqt._prepickuplot as       mqt_prepickuplot,
    mqt._prepickupsts as       mqt_prepickupsts,
    pos._filename_route as     pos_filename_route,
    pos._filename_timestamp as pos_filename_timestamp,
    pos._filename as           pos_filename,
    pos._filename_type as      pos_filename_type,
    pos._filename_id as        pos_filename_id,
    pos._history_id as         pos_history_id,
    pos._time_stamp as         pos_time_stamp,
    pos._crb_file_name as      pos_crb_file_name,
    pos._product_name as       pos_product_name,
    pos.lot_idnum as           pos_lot_idnum,
    pos._lotnum as             pos_lotnum,
    pos._lot as                pos_lot,
    pos._mcfilename as         pos_mcfilename,
    pos._filter as             pos_filter,
    pos._autochg as            pos_autochg,
    pos._basechg as            pos_basechg,
    pos._lane as               pos_lane,
    pos._productionid as       pos_productionid,
    pos._simproduct as         pos_simproduct,
    pos._dgspcbname as         pos_dgspcbname,
    pos._dgspcbrev as          pos_dgspcbrev,
    pos._dgspcbside as         pos_dgspcbside,
    pos._dgsrefpin as          pos_dgsrefpin,
    pos.lot_c as               pos_lot_c,
    pos._datagenmode as        pos_datagenmode,
    pos._mounthead as          pos_mounthead,
    pos._vstpath as            pos_vstpath,
    pos._targettact as         pos_targettact,
    pos._order as              pos_order,
    pos._lot_number as         pos_lot_number,
    pos.pos_idnum as           pos_idnum,
    pos._cadid as              pos_cadid,
    pos._x as                  pos_x,
    pos._y as                  pos_y,
    pos._a as                  pos_a,
    pos._parts as              pos_parts,
    pos._brm as                pos_brm,
    pos._turn as               pos_turn,
    pos._dturn as              pos_dturn,
    pos._ts as                 pos_ts,
    pos._ms as                 pos_ms,
    pos._ds as                 pos_ds,
    pos._np as                 pos_np,
    pos._dnp as                pos_dnp,
    pos._pu as                 pos_pu,
    pos._side as               pos_side,
    pos._dpu as                pos_dpu,
    pos._head as               pos_head,
    pos._dhead as              pos_dhead,
    pos._ihead as              pos_ihead,
    pos._b as                  pos_b,
    pos._pg as                 pos_pg,
    pos._s as                  pos_s,
    pos._rid as                pos_rid,
    pos.pos_c as               pos_c,
    pos._m as                  pos_m,
    pos._mb as                 pos_mb,
    pos._f as                  pos_f,
    pos._pr as                 pos_pr,
    pos._priseq as             pos_priseq,
    pos._p as                  pos_p,
    pos._pad as                pos_pad,
    pos._vw as                 pos_vw,
    pos._stdpos as             pos_stdpos,
    pos._land as               pos_land,
    pos._depend as             pos_depend,
    pos._chkflag as            pos_chkflag,
    pos._exchk as              pos_exchk,
    pos._grand as              pos_grand,
    pos._marea as              pos_marea,
    pos._rmset as              pos_rmset,
    pos._sh as                 pos_sh,
    pos._scandir1 as           pos_scandir1,
    pos._scandir2 as           pos_scandir2,
    pos._ohl as                pos_ohl,
    pos._ohr as                pos_ohr,
    pos._apcctrl as            pos_apcctrl,
    pos._wg as                 pos_wg,
    pos._skipnumber as         pos_skipnumber,
    aoi._filename as           aoi_filename,
    aoi._filename_type as      aoi_filename_type,
    aoi._filename_timestamp as aoi_filename_timestamp,
    aoi._filename_route as     aoi_filename_route,
    aoi._filename_id as        aoi_filename_id,
    aoi._aoi_pcbid as          aoi_aoi_pcbid,
    aoi._date_time as          aoi_date_time,
    aoi._cid as                aoi_cid,
    aoi._timestamp as          aoi_timestamp,
    aoi._crc as                aoi_crc,
    aoi._c2d as                aoi_c2d,
    aoi._recipename as         aoi_recipename,
    aoi._mid as                aoi_mid,
    aoi._p as                  aoi_p,
    aoi.cmp_idx as             aoi_cmp_idx,
    aoi._sc as                 aoi_sc,
    aoi._pid as                aoi_pid,
    aoi._fc as                 aoi_fc,
    aoi._cmp as                aoi_cmp,
    aoi._cc as                 aoi_cc,
    aoi._ref as                aoi_ref,
    aoi._type as               aoi_type,
    aoi._defect as             aoi_defect,
    aoi._insp_type as          aoi_insp_type,
    aoi._lead_id as            aoi_lead_id
from
    u03.index_info_mqt_no_view mqt
inner join
    crb.lot_position_data_no_view pos
on
    upper(pos._crb_file_name) = upper(mqt._mjsid)
and
    upper(pos._lot) = upper(mqt._lotname)
and
    pos.pos_idnum = mqt._idnum
inner join
    aoi.no_good_no_view aoi
on
    upper(aoi._c2d) = upper(mqt._pcb_id)
and
    upper(aoi._recipename) = upper(pos._dgspcbname)
and
    upper(aoi._ref) = upper(pos.pos_c)
;

create view u03.mqt_pos_data_aoi_good_view
as
select
    mqt._filename_route as     mqt_filename_route,
    mqt._machine_order as      mqt_machine_order,
    mqt._lane_no as            mqt_lane_no,
    mqt._stage_no as           mqt_stage_no,
    mqt._filename_timestamp as mqt_filename_timestamp,
    mqt._filename_id as        mqt_filename_id,
    mqt._pcb_serial as         mqt_pcb_serial,
    mqt._pcb_id as             mqt_pcb_id,
    mqt._output_no as          mqt_output_no,
    mqt._pcb_id_lot_no as      mqt_pcb_id_lot_no,
    mqt._pcb_id_serial_no as   mqt_pcb_id_serial_no,
    mqt._mjsid as              mqt_mjsid,
    mqt._bcrstatus as          mqt_bcrstatus,
    mqt._code as               mqt_code,
    mqt._lane as               mqt_lane,
    mqt._lotname as            mqt_lotname,
    mqt._lotnumber as          mqt_lotnumber,
    mqt._output as             mqt_output,
    mqt._planid as             mqt_planid,
    mqt._productid as          mqt_productid,
    mqt._rev as                mqt_rev,
    mqt._serial as             mqt_serial,
    mqt._serialstatus as       mqt_serialstatus,
    mqt._stage as              mqt_stage,
    mqt._b as                  mqt_b,
    mqt._idnum as              mqt_idnum,
    mqt._turn as               mqt_turn,
    mqt._ms as                 mqt_ms,
    mqt._ts as                 mqt_ts,
    mqt._fadd as               mqt_fadd,
    mqt._fsadd as              mqt_fsadd,
    mqt._nhadd as              mqt_nhadd,
    mqt._ncadd as              mqt_ncadd,
    mqt._fblkcode as           mqt_fblkcode,
    mqt._fblkserial as         mqt_fblkserial,
    mqt._nblkcode as           mqt_nblkcode,
    mqt._nblkserial as         mqt_nblkserial,
    mqt._reelid as             mqt_reelid,
    mqt._f as                  mqt_f,
    mqt._rcgx as               mqt_rcgx,
    mqt._rcgy as               mqt_rcgy,
    mqt._rcga as               mqt_rcga,
    mqt._tcx as                mqt_tcx,
    mqt._tcy as                mqt_tcy,
    mqt._mposirecx as          mqt_mposirecx,
    mqt._mposirecy as          mqt_mposirecy,
    mqt._mposireca as          mqt_mposireca,
    mqt._mposirecz as          mqt_mposirecz,
    mqt._thmax as              mqt_thmax,
    mqt._thave as              mqt_thave,
    mqt._mntcx as              mqt_mntcx,
    mqt._mntcy as              mqt_mntcy,
    mqt._mntca as              mqt_mntca,
    mqt._tlx as                mqt_tlx,
    mqt._tly as                mqt_tly,
    mqt._inspectarea as        mqt_inspectarea,
    mqt._didnum as             mqt_didnum,
    mqt._ds as                 mqt_ds,
    mqt._dispenseid as         mqt_dispenseid,
    mqt._parts as              mqt_parts,
    mqt._warpz as              mqt_warpz,
    mqt._prepickuplot as       mqt_prepickuplot,
    mqt._prepickupsts as       mqt_prepickupsts,
    pos._filename_route as     pos_filename_route,
    pos._filename_timestamp as pos_filename_timestamp,
    pos._filename as           pos_filename,
    pos._filename_type as      pos_filename_type,
    pos._filename_id as        pos_filename_id,
    pos._history_id as         pos_history_id,
    pos._time_stamp as         pos_time_stamp,
    pos._crb_file_name as      pos_crb_file_name,
    pos._product_name as       pos_product_name,
    pos.lot_idnum as           pos_lot_idnum,
    pos._lotnum as             pos_lotnum,
    pos._lot as                pos_lot,
    pos._mcfilename as         pos_mcfilename,
    pos._filter as             pos_filter,
    pos._autochg as            pos_autochg,
    pos._basechg as            pos_basechg,
    pos._lane as               pos_lane,
    pos._productionid as       pos_productionid,
    pos._simproduct as         pos_simproduct,
    pos._dgspcbname as         pos_dgspcbname,
    pos._dgspcbrev as          pos_dgspcbrev,
    pos._dgspcbside as         pos_dgspcbside,
    pos._dgsrefpin as          pos_dgsrefpin,
    pos.lot_c as               pos_lot_c,
    pos._datagenmode as        pos_datagenmode,
    pos._mounthead as          pos_mounthead,
    pos._vstpath as            pos_vstpath,
    pos._targettact as         pos_targettact,
    pos._order as              pos_order,
    pos._lot_number as         pos_lot_number,
    pos.pos_idnum as           pos_idnum,
    pos._cadid as              pos_cadid,
    pos._x as                  pos_x,
    pos._y as                  pos_y,
    pos._a as                  pos_a,
    pos._parts as              pos_parts,
    pos._brm as                pos_brm,
    pos._turn as               pos_turn,
    pos._dturn as              pos_dturn,
    pos._ts as                 pos_ts,
    pos._ms as                 pos_ms,
    pos._ds as                 pos_ds,
    pos._np as                 pos_np,
    pos._dnp as                pos_dnp,
    pos._pu as                 pos_pu,
    pos._side as               pos_side,
    pos._dpu as                pos_dpu,
    pos._head as               pos_head,
    pos._dhead as              pos_dhead,
    pos._ihead as              pos_ihead,
    pos._b as                  pos_b,
    pos._pg as                 pos_pg,
    pos._s as                  pos_s,
    pos._rid as                pos_rid,
    pos.pos_c as               pos_c,
    pos._m as                  pos_m,
    pos._mb as                 pos_mb,
    pos._f as                  pos_f,
    pos._pr as                 pos_pr,
    pos._priseq as             pos_priseq,
    pos._p as                  pos_p,
    pos._pad as                pos_pad,
    pos._vw as                 pos_vw,
    pos._stdpos as             pos_stdpos,
    pos._land as               pos_land,
    pos._depend as             pos_depend,
    pos._chkflag as            pos_chkflag,
    pos._exchk as              pos_exchk,
    pos._grand as              pos_grand,
    pos._marea as              pos_marea,
    pos._rmset as              pos_rmset,
    pos._sh as                 pos_sh,
    pos._scandir1 as           pos_scandir1,
    pos._scandir2 as           pos_scandir2,
    pos._ohl as                pos_ohl,
    pos._ohr as                pos_ohr,
    pos._apcctrl as            pos_apcctrl,
    pos._wg as                 pos_wg,
    pos._skipnumber as         pos_skipnumber,
    aoi._filename as           aoi_filename,
    aoi._filename_type as      aoi_filename_type,
    aoi._filename_timestamp as aoi_filename_timestamp,
    aoi._filename_route as     aoi_filename_route,
    aoi._filename_id as        aoi_filename_id,
    aoi._aoi_pcbid as          aoi_aoi_pcbid,
    aoi._date_time as          aoi_date_time,
    aoi._cid as                aoi_cid,
    aoi._timestamp as          aoi_timestamp,
    aoi._crc as                aoi_crc,
    aoi._c2d as                aoi_c2d,
    aoi._recipename as         aoi_recipename,
    aoi._mid as                aoi_mid,
    aoi._p as                  aoi_p,
    aoi.cmp_idx as             aoi_cmp_idx,
    aoi._sc as                 aoi_sc,
    aoi._pid as                aoi_pid,
    aoi._fc as                 aoi_fc
from
    u03.index_info_mqt_no_view mqt
inner join
    crb.lot_position_data_no_view pos
on
    upper(pos._crb_file_name) = upper(mqt._mjsid)
and
    upper(pos._lot) = upper(mqt._lotname)
and
    pos.pos_idnum = mqt._idnum
inner join
    aoi.good_no_view aoi
on
    upper(aoi._c2d) = upper(mqt._pcb_id)
and
    upper(aoi._recipename) = upper(pos._dgspcbname)
;

create view u01.pa_pcb_status_per_machine_view
as
select 
    ftf._filename_route,
    ufd._machine_order,
    ufd._lane_no,
    ufd._stage_no,
    ftf._filename_timestamp,
    -- ftf._filename,
    -- ftf._filename_type,
    ftf._filename_id,
    -- ufd._filename_id,
    -- ufd._date,
    ufd._pcb_serial,
    ufd._pcb_id,
    -- ufd._output_no,
    -- ufd._pcb_id_lot_no,
    -- ufd._pcb_id_serial_no
    -- upi._filename_id,
    -- upi._bcrstatus,
    -- upi._code,
    -- upi._lane,
    upi._lotname,
    upi._lotnumber,
    upi._output,
    -- upi._planid,
    upi._productid,
    -- upi._rev,
    upi._serial,
    -- upi._serialstatus,
    -- upi._stage,
    -- i._filename_id,
    -- i._cid,
    -- i._timestamp,
    -- i._crc,
    i._c2d,
    i._recipename,
    -- i._mid,
    -- p._filename_id,
    -- p._p,
    -- p._cmp as cmp_idx,
    case
        when (p._cmp = -1) then 'PASS'
        when (p._cmp = 1) then 'FAIL'
        else 'UNKNOWN'
    END as aoi_status
    -- p._sc,
    -- p._pid,
    -- p._fc
from
    u01.filename_to_fid ftf
inner join
    u01.u0x_filename_data ufd
on
    ufd._filename_id = ftf._filename_id
inner join
    u01.pivot_information upi
on
    upi._filename_id = ftf._filename_id
inner join
    aoi.insp i
on
    upper(i._c2d) = upper(ufd._pcb_id)
inner join
    aoi.p p
on
    p._filename_id = i._filename_id
where
    ufd._output_no in ( 3, 4 )
order by
    ftf._filename_route,
    ufd._machine_order,
    ufd._lane_no,
    ufd._stage_no,
    ftf._filename_timestamp
;

create view u01.pa_pcb_status_per_machine_no_view
as
select 
    ftf._filename_route,
    ufd._machine_order,
    ufd._lane_no,
    ufd._stage_no,
    ftf._filename_timestamp,
    -- ftf._filename,
    -- ftf._filename_type,
    ftf._filename_id,
    -- ufd._filename_id,
    -- ufd._date,
    ufd._pcb_serial,
    ufd._pcb_id,
    -- ufd._output_no,
    -- ufd._pcb_id_lot_no,
    -- ufd._pcb_id_serial_no
    -- upi._filename_id,
    -- upi._bcrstatus,
    -- upi._code,
    -- upi._lane,
    upi._lotname,
    upi._lotnumber,
    upi._output,
    -- upi._planid,
    upi._productid,
    -- upi._rev,
    upi._serial,
    -- upi._serialstatus,
    -- upi._stage,
    -- i._filename_id,
    -- i._cid,
    -- i._timestamp,
    -- i._crc,
    i._c2d,
    i._recipename,
    -- i._mid,
    -- p._filename_id,
    -- p._p,
    -- p._cmp as cmp_idx,
    case
        when (p._cmp = -1) then 'PASS'
        when (p._cmp = 1) then 'FAIL'
        else 'UNKNOWN'
    END as aoi_status
    -- p._sc,
    -- p._pid,
    -- p._fc
from
    u01.filename_to_fid ftf
inner join
    u01.u0x_filename_data ufd
on
    ufd._filename_id = ftf._filename_id
inner join
    u01.pivot_information upi
on
    upi._filename_id = ftf._filename_id
inner join
    aoi.insp i
on
    upper(i._c2d) = upper(ufd._pcb_id)
inner join
    aoi.p p
on
    p._filename_id = i._filename_id
where
    ufd._output_no in ( 3, 4 )
-- order by
    -- ftf._filename_route,
    -- ufd._machine_order,
    -- ufd._lane_no,
    -- ufd._stage_no,
    -- ftf._filename_timestamp
;

