-- 
-- z_cass report_id
-- z_cass cassette
-- z_cass slot
-- z_cass subslot
-- z_cass comp_id
-- z_cass reel_id
-- z_cass feeder_id
-- z_cass stocked
-- z_cass remaining
-- z_cass comp_exhaust
-- z_cass pickup_count
-- z_cass place_count
-- z_cass pickup_error_count
-- z_cass pickup_miss_count
-- z_cass recog_error_count
-- z_cass shape_error_count
-- z_cass height_miss_count
-- z_cass coplanarity
-- z_cass need_for_current_product
-- z_cass other_error_count
-- z_cass colinearity_count
-- z_cass pickup_attempt_count
-- z_cass place_search_attempt_count
-- z_cass place_search_failure_count
-- z_cass vision_failures
-- z_cass initial_part_count
-- z_cass used_parts_count
-- z_cass table_no
-- z_cass table_slot
-- z_cass table_subslot
-- z_cass primary_pn
-- 
-- z_cass_header mgmt_report_id
-- z_cass_header report_id
-- z_cass_header product_id
-- z_cass_header equipment_id
-- z_cass_header lane_no
-- z_cass_header start_time
-- z_cass_header end_time
-- z_cass_header setup_id
-- z_cass_header nc_version
-- z_cass_header job_id
-- z_cass_header report_file
-- 
-- z_cass_header_kx_by_board mgmt_report_id
-- z_cass_header_kx_by_board report_id
-- z_cass_header_kx_by_board product_id
-- z_cass_header_kx_by_board equipment_id
-- z_cass_header_kx_by_board lane_no
-- z_cass_header_kx_by_board start_time
-- z_cass_header_kx_by_board end_time
-- z_cass_header_kx_by_board setup_id
-- z_cass_header_kx_by_board nc_version
-- z_cass_header_kx_by_board job_id
-- z_cass_header_kx_by_board report_file
-- 
-- z_cass_header_raw mgmt_report_id
-- z_cass_header_raw report_id
-- z_cass_header_raw product_id
-- z_cass_header_raw equipment_id
-- z_cass_header_raw lane_no
-- z_cass_header_raw start_time
-- z_cass_header_raw end_time
-- z_cass_header_raw setup_id
-- z_cass_header_raw nc_version
-- z_cass_header_raw job_id
-- z_cass_header_raw report_file
-- 
-- z_cass_kx_by_board report_id
-- z_cass_kx_by_board cassette
-- z_cass_kx_by_board slot
-- z_cass_kx_by_board subslot
-- z_cass_kx_by_board comp_id
-- z_cass_kx_by_board reel_id
-- z_cass_kx_by_board feeder_id
-- z_cass_kx_by_board stocked
-- z_cass_kx_by_board remaining
-- z_cass_kx_by_board comp_exhaust
-- z_cass_kx_by_board pickup_count
-- z_cass_kx_by_board place_count
-- z_cass_kx_by_board pickup_error_count
-- z_cass_kx_by_board pickup_miss_count
-- z_cass_kx_by_board recog_error_count
-- z_cass_kx_by_board shape_error_count
-- z_cass_kx_by_board height_miss_count
-- z_cass_kx_by_board coplanarity
-- z_cass_kx_by_board need_for_current_product
-- z_cass_kx_by_board other_error_count
-- z_cass_kx_by_board colinearity_count
-- z_cass_kx_by_board pickup_attempt_count
-- z_cass_kx_by_board place_search_attempt_count
-- z_cass_kx_by_board place_search_failure_count
-- z_cass_kx_by_board vision_failures
-- z_cass_kx_by_board initial_part_count
-- z_cass_kx_by_board used_parts_count
-- z_cass_kx_by_board table_no
-- z_cass_kx_by_board table_slot
-- z_cass_kx_by_board table_subslot
-- z_cass_kx_by_board primary_pn
-- 
-- z_cass_npm report_id
-- z_cass_npm lot
-- z_cass_npm stage
-- z_cass_npm tprod
-- z_cass_npm head
-- z_cass_npm fadd
-- z_cass_npm fsadd
-- z_cass_npm fblkcode
-- z_cass_npm fblkserial
-- z_cass_npm reelid
-- z_cass_npm tcnt
-- z_cass_npm tmiss
-- z_cass_npm rmiss
-- z_cass_npm hmiss
-- z_cass_npm fmiss
-- z_cass_npm mmiss
-- z_cass_npm board
-- z_cass_npm partsname
-- z_cass_npm place_count
-- z_cass_npm trsmiss
-- z_cass_npm timestamp
-- z_cass_npm reel_id
-- z_cass_npm feeder_id
-- 
-- z_cass_npm_by_board report_id
-- z_cass_npm_by_board lot
-- z_cass_npm_by_board stage
-- z_cass_npm_by_board tprod
-- z_cass_npm_by_board head
-- z_cass_npm_by_board fadd
-- z_cass_npm_by_board fsadd
-- z_cass_npm_by_board fblkcode
-- z_cass_npm_by_board fblkserial
-- z_cass_npm_by_board reelid
-- z_cass_npm_by_board tcnt
-- z_cass_npm_by_board tmiss
-- z_cass_npm_by_board rmiss
-- z_cass_npm_by_board hmiss
-- z_cass_npm_by_board fmiss
-- z_cass_npm_by_board mmiss
-- z_cass_npm_by_board board
-- z_cass_npm_by_board partsname
-- z_cass_npm_by_board place_count
-- z_cass_npm_by_board trsmiss
-- z_cass_npm_by_board timestamp
-- z_cass_npm_by_board reel_id
-- z_cass_npm_by_board feeder_id
-- 
-- z_cass_npm_hdr report_id
-- z_cass_npm_hdr product_id
-- z_cass_npm_hdr equipment_id
-- z_cass_npm_hdr start_time
-- z_cass_npm_hdr end_time
-- z_cass_npm_hdr setup_id
-- z_cass_npm_hdr nc_version
-- z_cass_npm_hdr lane_no
-- z_cass_npm_hdr job_id
-- z_cass_npm_hdr trx_productid
-- z_cass_npm_hdr stage
-- z_cass_npm_hdr timestamp
-- 
-- z_cass_npm_hdr_by_board report_id
-- z_cass_npm_hdr_by_board product_id
-- z_cass_npm_hdr_by_board equipment_id
-- z_cass_npm_hdr_by_board start_time
-- z_cass_npm_hdr_by_board end_time
-- z_cass_npm_hdr_by_board setup_id
-- z_cass_npm_hdr_by_board nc_version
-- z_cass_npm_hdr_by_board lane_no
-- z_cass_npm_hdr_by_board job_id
-- z_cass_npm_hdr_by_board trx_productid
-- z_cass_npm_hdr_by_board stage
-- z_cass_npm_hdr_by_board timestamp
-- 
-- z_cass_npm_hdr_raw report_id
-- z_cass_npm_hdr_raw product_id
-- z_cass_npm_hdr_raw equipment_id
-- z_cass_npm_hdr_raw start_time
-- z_cass_npm_hdr_raw end_time
-- z_cass_npm_hdr_raw setup_id
-- z_cass_npm_hdr_raw nc_version
-- z_cass_npm_hdr_raw lane_no
-- z_cass_npm_hdr_raw job_id
-- z_cass_npm_hdr_raw trx_productid
-- z_cass_npm_hdr_raw stage
-- z_cass_npm_hdr_raw timestamp
-- 
-- z_cass_npm_raw report_id
-- z_cass_npm_raw lot
-- z_cass_npm_raw stage
-- z_cass_npm_raw tprod
-- z_cass_npm_raw head
-- z_cass_npm_raw fadd
-- z_cass_npm_raw fsadd
-- z_cass_npm_raw fblkcode
-- z_cass_npm_raw fblkserial
-- z_cass_npm_raw reelid
-- z_cass_npm_raw tcnt
-- z_cass_npm_raw tmiss
-- z_cass_npm_raw rmiss
-- z_cass_npm_raw hmiss
-- z_cass_npm_raw fmiss
-- z_cass_npm_raw mmiss
-- z_cass_npm_raw board
-- z_cass_npm_raw partsname
-- z_cass_npm_raw place_count
-- z_cass_npm_raw trsmiss
-- z_cass_npm_raw timestamp
-- z_cass_npm_raw reel_id
-- z_cass_npm_raw feeder_id
-- 
-- z_cass_raw report_id
-- z_cass_raw cassette
-- z_cass_raw slot
-- z_cass_raw subslot
-- z_cass_raw comp_id
-- z_cass_raw reel_id
-- z_cass_raw feeder_id
-- z_cass_raw stocked
-- z_cass_raw remaining
-- z_cass_raw comp_exhaust
-- z_cass_raw pickup_count
-- z_cass_raw place_count
-- z_cass_raw pickup_error_count
-- z_cass_raw pickup_miss_count
-- z_cass_raw recog_error_count
-- z_cass_raw shape_error_count
-- z_cass_raw height_miss_count
-- z_cass_raw coplanarity
-- z_cass_raw need_for_current_product
-- z_cass_raw other_error_count
-- z_cass_raw colinearity_count
-- z_cass_raw pickup_attempt_count
-- z_cass_raw place_search_attempt_count
-- z_cass_raw place_search_failure_count
-- z_cass_raw vision_failures
-- z_cass_raw initial_part_count
-- z_cass_raw used_parts_count
-- z_cass_raw table_no
-- z_cass_raw table_slot
-- z_cass_raw table_subslot
-- z_cass_raw primary_pn

-- mrumore:cim8.5.0.1:orig> ./calgary.times.sh
-- + env TZ=Canada/Mountain date -d '2015-02-09 00:00:00' +%s
-- 1423465200
-- + env TZ=Canada/Mountain date -d '2015-02-10 00:00:00' +%s
-- 1423551600
-- + env TZ=Canada/Mountain date -d '2015-02-09 12:00:00' +%s
-- 1423508400
-- + env TZ=Canada/Mountain date -d '2015-02-10 12:00:00' +%s
-- 1423594800
-- + exit 0

-- select
--     -- zhr.mgmt_report_id
--     zhr.equipment_id as eqid,
--     eq.equipment_name as eqnm,
--     zhr.lane_no as lnno,
--     zr.slot as slot,
--     zr.subslot as sslot,
--     zr.comp_id as cid,
--     -- zhr.report_id,
--     -- zhr.product_id,
--     -- zhr.start_time,
--     zhr.end_time as etm,
--     -- zhr.setup_id,
--     -- zhr.nc_version,
--     -- zhr.job_id,
--     zhr.report_file as rfile
--     -- zr.report_id,
--     -- zr.cassette,
--     -- zr.reel_id,
--     -- zr.feeder_id,
--     -- zr.stocked,
--     -- zr.remaining,
--     -- zr.comp_exhaust,
--     -- zr.pickup_count,
--     -- zr.place_count,
--     -- zr.pickup_error_count,
--     -- zr.shape_error_count,
--     -- zr.height_miss_count,
--     -- zr.coplanarity,
--     -- zr.need_for_current_product,
--     -- zr.other_error_count,
--     -- zr.colinearity_count,
--     -- zr.pickup_attempt_count,
--     -- zr.place_search_attempt_count,
--     -- zr.place_search_failure_count,
--     -- zr.vision_failures,
--     -- zr.initial_part_count,
--     -- zr.used_parts_count,
--     -- zr.table_no,
--     -- zr.table_slot,
--     -- zr.table_subslot,
--     -- zr.primary_pn
-- from
--     z_cass_header_raw zhr
-- inner join
--     z_cass_raw zr
-- on
--     zhr.report_id = zr.report_id
-- left join
--     equipment eq
-- on
--     zhr.equipment_id = eq.equipment_id
-- where
--     zr.comp_id like '%50104991-012%'
-- and
--     zhr.end_time >= 1423465200
-- and
--     zhr.end_time <= 1423551600
-- order by
--     zhr.equipment_id asc,
--     zhr.report_id asc
-- go
-- 
-- select
--     -- zh.mgmt_report_id,
--     zh.equipment_id as eqid,
--     zh.lane_no as lnno,
--     z.slot as slot,
--     z.subslot as sslot,
--     z.comp_id as cid,
--     -- zh.report_id,
--     -- zh.product_id,
--     -- zh.start_time,
--     zh.end_time as etm,
--     -- zh.setup_id,
--     -- zh.nc_version,
--     -- zh.job_id,
--     zh.report_file as rfile
--     -- z.report_id,
--     -- z.cassette,
--     -- z.reel_id,
--     -- z.feeder_id,
--     -- z.stocked,
--     -- z.remaining,
--     -- z.comp_exhaust,
--     -- z.pickup_count,
--     -- z.place_count
--     -- z.pickup_error_count,
--     -- z.pickup_miss_count,
--     -- z.recog_error_count,
--     -- z.shape_error_count,
--     -- z.height_miss_count,
--     -- z.coplanarity,
--     -- z.need_for_current_product,
--     -- z.other_error_count,
--     -- z.colinearity_count,
--     -- z.pickup_attempt_count,
--     -- z.place_search_attempt_count,
--     -- z.place_search_failure_count,
--     -- z.vision_failures,
--     -- z.initial_part_count,
--     -- z.used_parts_count,
--     -- z.table_no,
--     -- z.table_slot,
--     -- z.table_subslot,
--     -- z.primary_pn
-- from
--     z_cass_header zh
-- inner join
--     z_cass z
-- on
--     zh.report_id = z.report_id
-- where
--     z.comp_id like '%50104991-012%'
-- and
--     zh.end_time >= 1423465200
-- and
--     zh.end_time <= 1423551600
-- order by
--     zh.equipment_id asc,
--     zh.report_id asc
-- go
-- 
-- select
--     count(*)
-- from
--     z_cass_header zh
-- inner join
--     z_cass z
-- on
--     zh.report_id = z.report_id
-- where
--     z.comp_id like '%50104991-012%'
-- and
--     zh.end_time >= 1423465200
-- and
--     zh.end_time <= 1423551600
-- go
-- 
-- select
--     count(*)
-- from
--     z_cass_header_raw zhr
-- inner join
--     z_cass_raw zr
-- on
--     zhr.report_id = zr.report_id
-- where
--     zr.comp_id like '%50104991-012%'
-- and
--     zhr.end_time >= 1423465200
-- and
--     zhr.end_time <= 1423551600
-- go
-- 
-- select
--     zhr.equipment_id as eqid,
--     count(*)
-- from
--     z_cass_header_raw zhr
-- inner join
--     z_cass_raw zr
-- on
--     zhr.report_id = zr.report_id
-- where
--     zr.comp_id like '%50104991-012%'
-- and
--     zhr.end_time >= 1423465200
-- and
--     zhr.end_time <= 1423551600
-- group by
--     zhr.equipment_id 
-- order by
--     zhr.equipment_id asc
-- go
-- 
-- select
--     zh.equipment_id as eqid,
--     count(*)
-- from
--     z_cass_header zh
-- inner join
--     z_cass z
-- on
--     zh.report_id = z.report_id
-- where
--     z.comp_id like '%50104991-012%'
-- and
--     zh.end_time >= 1423465200
-- and
--     zh.end_time <= 1423551600
-- group by
--     zh.equipment_id 
-- order by
--     zh.equipment_id asc
-- go

select
    -- zhr.mgmt_report_id
    -- zhr.equipment_id,
    eq.equipment_name,
    zhr.lane_no,
    zhr.report_id,
    zr.slot,
    zr.subslot,
    zr.comp_id,
    -- zhr.product_id,
    zhr.start_time,
    zhr.end_time,
    -- zhr.setup_id,
    -- zhr.nc_version,
    -- zhr.job_id,
    -- zhr.report_file,
    -- zr.report_id,
    -- zr.cassette,
    zr.reel_id,
    -- zr.feeder_id,
    -- zr.stocked,
    -- zr.remaining,
    -- zr.comp_exhaust,
    zr.pickup_count,
    zr.place_count,
    -- zr.pickup_error_count,
    -- zr.shape_error_count,
    -- zr.height_miss_count,
    -- zr.coplanarity,
    -- zr.need_for_current_product,
    -- zr.other_error_count,
    -- zr.colinearity_count,
    -- zr.pickup_attempt_count,
    -- zr.place_search_attempt_count,
    -- zr.place_search_failure_count,
    -- zr.vision_failures,
    -- zr.initial_part_count,
    -- zr.used_parts_count,
    -- zr.table_no,
    -- zr.table_slot,
    -- zr.table_subslot,
    zr.primary_pn
from
    z_cass_header_raw zhr
left join
    z_cass_raw zr
on
    zhr.report_id = zr.report_id
left join
    equipment eq
on
    zhr.equipment_id = eq.equipment_id
where
    zr.comp_id like '%50104991-012%'
and
    zhr.end_time >= 1423465200
and
    zhr.end_time <= 1423551600
order by
    zhr.equipment_id asc,
    zhr.report_id asc,
    zr.slot asc,
    zr.subslot asc
go
