# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded cfgdata 1.0 [list source [file join $dir cfgdata.tcl]]
package ifneeded checkenv 1.0 [list source [file join $dir checkenv.tcl]]
package ifneeded checkretval 1.0 [list source [file join $dir checkretval.tcl]]
package ifneeded chooseone 1.0 [list source [file join $dir chooseone.tcl]]
package ifneeded cleis 1.0 [list source [file join $dir cleis.tcl]]
package ifneeded db 1.0 [list source [file join $dir db.tcl]]
package ifneeded getoptval 1.0 [list source [file join $dir getoptval.tcl]]
package ifneeded hugftp 1.0 [list source [file join $dir hugftp.tcl]]
package ifneeded hughardware 1.0 [list source [file join $dir hughardware.tcl]]
package ifneeded hugtelnet 1.0 [list source [file join $dir hugtelnet.tcl]]
package ifneeded hugtl1 1.0 [list source [file join $dir hugtl1.tcl]]
package ifneeded lock 1.0 [list source [file join $dir lock.tcl]]
package ifneeded nscripts 1.0 [list source [file join $dir nscripts.tcl]]
package ifneeded scripts 1.0 [list source [file join $dir scripts.tcl]]
